apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  namespace: upbound-system
spec:
  credentials:
     source: Secret
     secretRef:
        namespace: upbound-system
        name: aws-creds
        key: creds
